---
driver:
  name: digitalocean

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    driver:
      name: digitalocean
      image: centos-6-5-x64

suites:
  - name: default
    run_list:
      - recipe[loganov-nginx::default]
    attributes:
